version: '3.0'

services:
    sql:
      container_name: sql
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
        - "ACCEPT_EULA=Y"
        - "SA_PASSWORD=passplease"
      ports:
          - 1433:1433
      networks:
        - app

networks:
  app:
    driver: bridge        