USE [master]
GO
ALTER DATABASE [pokemon-pro] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
DROP DATABASE [pokemon-pro]
GO
ALTER DATABASE [pokemon-pre] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
DROP DATABASE [pokemon-pre]
GO
ALTER DATABASE [pokemon-dev] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
DROP DATABASE [pokemon-dev]
GO
ALTER DATABASE [pokemon-local] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
DROP DATABASE [pokemon-local]
GO

